# Generated by Django 4.2.16 on 2025-04-23 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grievance_social_protection', '0018_alter_comment_user_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='reporter_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reporter_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
