# Generated by Django 4.2.16 on 2025-05-14 13:45

import core.fields
import core.models.base_mutation
import core.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_exportablequerymodel_file_format'),
        ('grievance_social_protection', '0019_historicalticket_reporter_info_ticket_reporter_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAttachmentType',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.SmallIntegerField(db_column='TicketAttachmentTypeId', primary_key=True, serialize=False)),
                ('ticket_attachment_type', models.CharField(db_column='TicketAttachmentType', max_length=50)),
                ('is_autogenerated', models.BooleanField(default=False)),
                ('ticket_general_type', models.CharField(choices=[('URL', 'Url'), ('FILE', 'File')], default='FILE', max_length=10)),
            ],
            options={
                'db_table': 'ticket_TicketAttachment_TicketAttachmentType',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='RECEIVED', max_length=20),
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.UUIDField(blank=True, db_column='LegacyID', null=True)),
                ('general_type', models.CharField(choices=[('URL', 'Url'), ('FILE', 'File')], default='FILE', max_length=4)),
                ('type', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('date', core.fields.DateField(blank=True, default=core.utils.TimeUtils.now)),
                ('filename', models.TextField(blank=True, null=True)),
                ('mime', models.TextField(blank=True, null=True)),
                ('module', models.TextField(null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('document', models.TextField(blank=True, null=True)),
                ('predefined_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_dropdown', to='grievance_social_protection.ticketattachmenttype')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachments', to='grievance_social_protection.ticket')),
            ],
            options={
                'db_table': 'ticket_TicketAttachment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AttachmentMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachment', to='core.mutationlog')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='grievance_social_protection.ticketattachment')),
            ],
            options={
                'db_table': 'ticket_AttachmentMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.base_mutation.ObjectMutation),
        ),
    ]
